# Generated by Django 3.2.9 on 2022-02-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0015_wyniki_kara_punktowa'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki',
            name='amunicja_klubowa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='wyniki',
            name='bron_klubowa',
            field=models.BooleanField(default=False),
        ),
    ]
