# Generated by Django 3.2.9 on 2022-02-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0016_auto_20220210_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wyniki',
            name='amunicja_klubowa',
            field=models.BooleanField(default=False, verbose_name='Amunicja klubowa'),
        ),
        migrations.AlterField(
            model_name='wyniki',
            name='bron_klubowa',
            field=models.BooleanField(default=False, verbose_name='Broń klubowa'),
        ),
    ]
