# Generated by Django 3.2.9 on 2022-06-28 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wyniki', '0017_auto_20220617_0614'),
        ('zawody', '0015_auto_20220621_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Opłacono')),
                ('turniej', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zawody.turniej')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_pay', models.FloatField(default=0)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Orders.order')),
                ('wynik', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wyniki.wyniki')),
            ],
        ),
    ]
