# Generated by Django 3.2.9 on 2022-06-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='to_pay',
            new_name='is_paid',
        ),
    ]
