# Generated by Django 3.2.9 on 2022-06-28 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Orders', '0002_rename_to_pay_orderitem_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='zawodnik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
