# Generated by Django 3.2.9 on 2022-06-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_order_zawodnik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Opłacono'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Opłacono'),
        ),
    ]
