# Generated by Django 3.2.9 on 2022-06-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0017_auto_20220617_0614'),
        ('Orders', '0005_orderitem_to_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Orders.order'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='wynik',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wyniki.wyniki'),
        ),
    ]
